spring:
  profiles:
    active: local
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000

  application:
    name: fanren-ai-code-mother-backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.zhimaaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
